# Generated by Django 4.2.5 on 2023-09-28 01:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0004_rename_usuario_usuario_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
