# Generated by Django 4.2.5 on 2023-09-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_usuario_user_usuario_email_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('RUC', models.CharField(max_length=32)),
                ('whatsapp', models.CharField(max_length=22)),
                ('fb', models.URLField(blank=True, null=True)),
                ('ig', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rubro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.negocio')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='negocio',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.rubro'),
        ),
    ]
