# Generated by Django 4.2.5 on 2023-11-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_rename_nombre_categoria_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='negocio',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.negocio'),
            preserve_default=False,
        ),
    ]
