# Generated by Django 4.2.5 on 2023-11-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_inventario_negocio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
    ]
