# Generated by Django 4.2.5 on 2023-11-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_remove_inventario_negocio_remove_inventario_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
