# Generated by Django 4.2.5 on 2023-11-08 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto'),
        ),
    ]
