# Generated by Django 4.2.4 on 2023-11-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_producto_negocio_producto_proveedor_producto_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='pais',
            new_name='pais_fk',
        ),
    ]
