# Generated by Django 4.2.4 on 2023-11-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_rename_pais_departamento_pais_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distrito',
            old_name='provincia',
            new_name='provincia_pk',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='departamento',
            new_name='departamento_pk',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='distrito',
            new_name='distrito_pk',
        ),
    ]
