# Generated by Django 4.2.4 on 2023-11-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_rename_provincia_distrito_provincia_pk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distrito',
            old_name='provincia_pk',
            new_name='provincia_fk',
        ),
        migrations.RenameField(
            model_name='negocio',
            old_name='pais',
            new_name='pais_fk',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='departamento_pk',
            new_name='departamento_fk',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='nombre_rol',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='rubro',
            old_name='nombre_rubro',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='distrito_pk',
            new_name='distrito_fk',
        ),
        migrations.RenameField(
            model_name='usuarionegocio',
            old_name='negocio',
            new_name='negocio_fk',
        ),
        migrations.RenameField(
            model_name='usuarionegocio',
            old_name='rol',
            new_name='rol_fk',
        ),
        migrations.RenameField(
            model_name='usuarionegocio',
            old_name='usuario',
            new_name='usuario_fk',
        ),
    ]
