# Generated by Django 4.2.4 on 2023-11-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_rename_provincia_pk_distrito_provincia_fk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ubicacion',
            new_name='ubicacion_fk',
        ),
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='producto',
            new_name='producto_fk',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_fk',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='negocio',
            new_name='negocio_fk',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='proveedor_fk',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_proveedor',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='estado',
            new_name='estado_fk',
        ),
    ]
